const productReviews = [
  {
    product: '65633',
    page: 0,
    count: 5,
    results: [
      {
        review_id: 1175680,
        rating: 5,
        summary: "It's good",
        recommend: true,
        response: null,
        body: 'I love this item so much',
        date: '2022-04-06T00:00:00.000Z',
        reviewer_name: 'fan',
        helpfulness: 29,
        photos: [],
      },
      {
        review_id: 1176122,
        rating: 4,
        summary: 'Still Getting the Fit Right...',
        recommend: true,
        response: null,
        body: "They need to change their sizing, it's not me, it's them.",
        date: '2022-04-12T00:00:00.000Z',
        reviewer_name: 'FitPug',
        helpfulness: 3,
        photos: [
          {
            id: 2259384,
            url: 'http://res.cloudinary.com/dmb8pc511/image/upload/v1649792965/tfjalf62syrdmd68chj8.jpg',
          },
        ],
      },
      {
        review_id: 1176288,
        rating: 4,
        summary: 'aaaaaaaaa',
        recommend: true,
        response: null,
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n',
        date: '2022-04-14T00:00:00.000Z',
        reviewer_name: 'pizza',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 1176166,
        rating: 5,
        summary: '',
        recommend: true,
        response: null,
        body: 'This is a great product, I love the fit! thank you for stocking such a great product!',
        date: '2022-04-12T00:00:00.000Z',
        reviewer_name: 'pugman',
        helpfulness: 0,
        photos: [
          {
            id: 2259420,
            url: 'http://res.cloudinary.com/dmb8pc511/image/upload/v1649796498/ioxis2vchgoohgmfwmcj.jpg',
          },
          {
            id: 2259421,
            url: 'http://res.cloudinary.com/dmb8pc511/image/upload/v1649796498/n3czkppqivdwene6weim.jpg',
          },
        ],
      },
      {
        review_id: 1176163,
        rating: 4,
        summary: 'Happy',
        recommend: true,
        response: null,
        body: 'This was so great, I really loved it, thank you for a great product!',
        date: '2022-04-12T00:00:00.000Z',
        reviewer_name: 'happycustomer',
        helpfulness: 0,
        photos: [],
      },
    ],
  },
  {
    product: '65634',
    page: 0,
    count: 5,
    results: [
      {
        review_id: 1176197,
        rating: 4,
        summary: 'Its great!',
        recommend: true,
        response: null,
        body: "These pants are super comfortable. My motherinlaw really liked them too!! Finally getting on the right page with her.. i'll be recommending these to my friends!",
        date: '2022-04-12T00:00:00.000Z',
        reviewer_name: 'FourTimestheCharm',
        helpfulness: 4,
        photos: [],
      },
      {
        review_id: 1176186,
        rating: 3,
        summary: 'Its alright, but the seams are scratchy',
        recommend: true,
        response: null,
        body: 'The look is great, but the seams are a little itchy during the day. If youre okay with that, then its a good product. I wouldnt necessarily buy again though.',
        date: '2022-04-12T00:00:00.000Z',
        reviewer_name: 'OkayPal',
        helpfulness: 1,
        photos: [],
      },
      {
        review_id: 1176187,
        rating: 3,
        summary: 'Nice One!',
        recommend: true,
        response: null,
        body: "I just LOVE finding new clothes!! I have a new gig in Silicon Valley so I wanted to make a good first impression. They're comfortable for long coding sessions, and I even sleep in them a LOT, theyre just that comfortable. I'll be ordering more for the XMas holidays!",
        date: '2022-04-12T00:00:00.000Z',
        reviewer_name: 'ExcitedAllTheTime',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 1176183,
        rating: 5,
        summary: 'No Reviews Here??',
        recommend: true,
        response: null,
        body: "I'll leave the first review here then. The Slacker's Slacks are the perfect complement to any top. They are good professionally and at home. They make a great first impression and are comfortable throughout the day. The fabric breaths well, and has a slight stress for comfort. ",
        date: '2022-04-12T00:00:00.000Z',
        reviewer_name: 'MrSpeaksUp',
        helpfulness: 0,
        photos: [],
      },
    ],
  },
  {
    product: '65635',
    page: 0,
    count: 5,
    results: [
      {
        review_id: 1176169,
        rating: 5,
        summary: 'A 9/10. what a find!',
        recommend: true,
        response: null,
        body: 'These shoes really improved my tennis experience. Im ready to face off against Bill!',
        date: '2022-04-12T00:00:00.000Z',
        reviewer_name: 'Fred',
        helpfulness: 6,
        photos: [
          {
            id: 2259422,
            url: 'https://pyxis.nymag.com/v1/imgs/42c/e20/69c48f5e8a2e2a3c1e1a9a467d22335fd9-03-tennis-shoes.jpg',
          },
        ],
      },
      {
        review_id: 1176297,
        rating: 5,
        summary: 'Absolutely Cool',
        recommend: true,
        response: null,
        body: 'I’ll buy my shoes here again and again. Why should I have write down such many words!!!!',
        date: '2022-04-14T00:00:00.000Z',
        reviewer_name: 'QQWANG',
        helpfulness: 4,
        photos: [],
      },
      {
        review_id: 1176171,
        rating: 3,
        summary: 'Not bad at all',
        recommend: true,
        response: null,
        body: 'its really a good find. a solid 3/5',
        date: '2022-04-12T00:00:00.000Z',
        reviewer_name: 'NotBadBill',
        helpfulness: 4,
        photos: [],
      },
      {
        review_id: 1176298,
        rating: 5,
        summary: '您好',
        recommend: true,
        response: null,
        body: '親愛的客戶您好：恭喜您符合降息資格！請洽車貸李經理LINE/☎️0901056597如需資金增貸90萬月付1萬1，機車可40萬，不看財力遲繳',
        date: '2022-04-14T00:00:00.000Z',
        reviewer_name: '李',
        helpfulness: 0,
        photos: [],
      },
      {
        review_id: 1176202,
        rating: 2,
        summary: 'A 2/10. bad!',
        recommend: true,
        response: null,
        body: 'Wear out too quickly!!',
        date: '2022-04-12T00:00:00.000Z',
        reviewer_name: 'Joel',
        helpfulness: 0,
        photos: [
          {
            id: 2259438,
            url: 'https://pyxis.nymag.com/v1/imgs/42c/e20/69c48f5e8a2e2a3c1e1a9a467d22335fd9-03-tennis-shoes.jpg',
          },
        ],
      },
    ],
  },
];

export default productReviews;
